/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.31
 * Generated at: 2025-01-07 16:49:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class handbook_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/view/ViewShare/header.jsp", Long.valueOf(1736268515856L));
    _jspx_dependants.put("/view/ViewShare/footer.jsp", Long.valueOf(1736255848937L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("<title>Cẩm Nang Y Tế</title>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/bootstrap/bootstrap.min.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/handbook.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/style.css\" />\r\n");
      out.write("\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css\"\r\n");
      out.write("	rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- header -->\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<title>Header</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/header.css\" />\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/bootstrap/bootstrap.min.css\" />\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!--header start-->\r\n");
      out.write("	<header class=\"header\">\r\n");
      out.write("		<div class=\"headerTop\">\r\n");
      out.write("			<div\r\n");
      out.write("				class=\"container d-flex justify-content-between align-items-center\">\r\n");
      out.write("				<div class=\"hotline\">\r\n");
      out.write("					Hotline Tư vấn:\r\n");
      out.write("					<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\"\r\n");
      out.write("						fill=\"currentColor\" class=\"bi bi-telephone-fill\"\r\n");
      out.write("						viewBox=\"0 0 16 16\">\r\n");
      out.write("              <path fill-rule=\"evenodd\"\r\n");
      out.write("							d=\"M1.885.511a1.745 1.745 0 0 1 2.61.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.68.68 0 0 0 .178.643l2.457 2.457a.68.68 0 0 0 .644.178l2.189-.547a1.75 1.75 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.6 18.6 0 0 1-7.01-4.42 18.6 18.6 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877z\" />\r\n");
      out.write("            </svg>\r\n");
      out.write("					1808 1309\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"login d-flex align-items-center position-relative\">\r\n");
      out.write("					<span class=\"name\">Subeo dangiu</span>\r\n");
      out.write("					<li class=\"nav-item dropdown\"><i class=\"bi bi-person-circle\"></i>\r\n");
      out.write("						<ul class=\"dropdown-menu\">\r\n");
      out.write("							<li><a class=\"dropdown-item\"\r\n");
      out.write("								href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/view/Login.jsp\"><i\r\n");
      out.write("									class=\"bi bi-box-arrow-right\"></i> Đăng xuất </a></li>\r\n");
      out.write("						</ul></li>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!--navbar start-->\r\n");
      out.write("		<nav class=\"navbar navbar-expand-lg\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"row w-100 align-items-center\">\r\n");
      out.write("					<div class=\"col-lg-3 col-md-4 col-sm-6\">\r\n");
      out.write("						<a class=\"navbar-brand text-pink\"\r\n");
      out.write("							href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/view/homepage.jsp\">\r\n");
      out.write("							<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/logoWHM.png\"\r\n");
      out.write("							alt=\"Women's Health Maternity\" />\r\n");
      out.write("						</a>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-lg-9 col-md-8 col-sm-6\">\r\n");
      out.write("						<button class=\"navbar-toggler\" type=\"button\"\r\n");
      out.write("							data-bs-toggle=\"collapse\" data-bs-target=\"#navbarNav\"\r\n");
      out.write("							aria-controls=\"navbarNav\" aria-expanded=\"false\"\r\n");
      out.write("							aria-label=\"Toggle navigation\">\r\n");
      out.write("							<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("						</button>\r\n");
      out.write("						<div class=\"collapse navbar-collapse\" id=\"navbarNav\">\r\n");
      out.write("							<ul class=\"navbar-nav ms-auto\">\r\n");
      out.write("								<!-- đặt khám -->\r\n");
      out.write("								<li class=\"nav-item dropdown\"><a\r\n");
      out.write("									class=\"nav-link dropdown-toggle\" href=\"#\" id=\"bookingDropdown\"\r\n");
      out.write("									role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("										Đặt lịch khám </a>\r\n");
      out.write("									<ul class=\"dropdown-menu\" aria-labelledby=\"bookingDropdown\">\r\n");
      out.write("										<li><a class=\"dropdown-item\"\r\n");
      out.write("											href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/bookingDoctor\">Bác\r\n");
      out.write("												Sĩ</a></li>\r\n");
      out.write("										<li><a class=\"dropdown-item\"\r\n");
      out.write("											href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/bookingMedilFaci\">Cơ\r\n");
      out.write("												sở y tế</a></li>\r\n");
      out.write("									</ul></li>\r\n");
      out.write("								<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("									href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/QaA\">Hỏi đáp bác\r\n");
      out.write("										sĩ</a></li>\r\n");
      out.write("								<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("									href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/healthRecord\">Hồ\r\n");
      out.write("										sơ sức khỏe</a></li>\r\n");
      out.write("								<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("									href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/handbook\">Cẩm nang</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</nav>\r\n");
      out.write("		<!--navbar end-->\r\n");
      out.write("	</header>\r\n");
      out.write("	<!--header end-->\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/bootstrap/bootstrap.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("	<div class=\"main\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<!-- Cột bên trái -->\r\n");
      out.write("				<div class=\"main-left-col col-lg-10 col-md-7 col-sm-12\">\r\n");
      out.write("					<div\r\n");
      out.write("						class=\"main-left-cards row row-cols-lg-3 row-cols-md-2 row-cols-1 g-4\">\r\n");
      out.write("						<!-- cart -->\r\n");
      out.write("						<div class=\"card\"\r\n");
      out.write("							onclick=\"window.location.href='../listCamNang/cart1.html'\"\r\n");
      out.write("							style=\"cursor: pointer\">\r\n");
      out.write("							<img src=\"../img/hon-nhau-co-lay-sui-mao-ga-khong-1.jpg\"\r\n");
      out.write("								class=\"card-img-top\" alt=\"...\" />\r\n");
      out.write("							<div class=\"card-body\">\r\n");
      out.write("								<h5 class=\"card-title\">Hôn nhau có gây xùi mào gà không?\r\n");
      out.write("									Bốn cách phòng bệnh</h5>\r\n");
      out.write("								<p class=\"card-text\">Nhiều cặp đôi thắc mắc là khi hôn nhau\r\n");
      out.write("									có lây sùi mào gà không? Hôn nhau được xem là một cách truyền\r\n");
      out.write("									tải tình cảm, mang đến cảm giác hưng phân cho các cặp đôi. Vậy\r\n");
      out.write("									khi có lây sùi mào gà không? Bệnh sùi mào gà có lây qua đường\r\n");
      out.write("									miệng không? Hãy theo dõi bài viết sau đây để giải đáp các thắc\r\n");
      out.write("									mắc trên.</p>\r\n");
      out.write("								<small class=\"viewer\"> <span>10/10/2024</span>\r\n");
      out.write("									<div>\r\n");
      out.write("										<svg width=\"15\" height=\"11\" viewBox=\"0 0 15 11\" fill=\"none\"\r\n");
      out.write("											class=\"icon-color\" xmlns=\"http://www.w3.org/2000/svg\">\r\n");
      out.write("                        <path\r\n");
      out.write("												d=\"M14.9698 5.33C14.3817 3.80882 13.3608 2.49331 12.0332 1.54604C10.7056 0.598778 9.12953 0.0612865 7.49979 0C5.87005 0.0612865 4.29398 0.598778 2.96639 1.54604C1.6388 2.49331 0.617868 3.80882 0.0297873 5.33C-0.00992909 5.43985 -0.00992909 5.56015 0.0297873 5.67C0.617868 7.19118 1.6388 8.50669 2.96639 9.45396C4.29398 10.4012 5.87005 10.9387 7.49979 11C9.12953 10.9387 10.7056 10.4012 12.0332 9.45396C13.3608 8.50669 14.3817 7.19118 14.9698 5.67C15.0095 5.56015 15.0095 5.43985 14.9698 5.33ZM7.49979 10C4.84979 10 2.04979 8.035 1.03479 5.5C2.04979 2.965 4.84979 1 7.49979 1C10.1498 1 12.9498 2.965 13.9648 5.5C12.9498 8.035 10.1498 10 7.49979 10Z\"\r\n");
      out.write("												fill=\"#005594\"></path>\r\n");
      out.write("                        <path\r\n");
      out.write("												d=\"M7.49976 2.5C6.90641 2.5 6.32639 2.67595 5.83305 3.00559C5.3397 3.33524 4.95518 3.80377 4.72812 4.35195C4.50106 4.90013 4.44165 5.50333 4.5574 6.08527C4.67316 6.66721 4.95888 7.20176 5.37844 7.62132C5.79799 8.04088 6.33254 8.3266 6.91449 8.44236C7.49643 8.55811 8.09963 8.4987 8.64781 8.27164C9.19599 8.04458 9.66452 7.66006 9.99417 7.16671C10.3238 6.67336 10.4998 6.09334 10.4998 5.5C10.4998 4.70435 10.1837 3.94129 9.62108 3.37868C9.05847 2.81607 8.29541 2.5 7.49976 2.5ZM7.49976 7.5C7.10419 7.5 6.71751 7.3827 6.38862 7.16294C6.05972 6.94318 5.80337 6.63082 5.652 6.26537C5.50062 5.89991 5.46102 5.49778 5.53819 5.10982C5.61536 4.72186 5.80584 4.36549 6.08554 4.08579C6.36525 3.80608 6.72161 3.6156 7.10958 3.53843C7.49754 3.46126 7.89967 3.50087 8.26512 3.65224C8.63058 3.80362 8.94293 4.05996 9.1627 4.38886C9.38246 4.71776 9.49976 5.10444 9.49976 5.5C9.49976 6.03043 9.28904 6.53914 8.91397 6.91421C8.5389 7.28929 8.03019 7.5 7.49976 7.5Z\"\r\n");
      out.write("												fill=\"#005594\"></path>\r\n");
      out.write("                      </svg>\r\n");
      out.write("										<span>500</span>\r\n");
      out.write("									</div>\r\n");
      out.write("								</small>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- cart -->\r\n");
      out.write("						<div class=\"card\"\r\n");
      out.write("							onclick=\"window.location.href='../listCamNang/cart1.html'\"\r\n");
      out.write("							style=\"cursor: pointer\">\r\n");
      out.write("							<img src=\"../img/hon-nhau-co-lay-sui-mao-ga-khong-1.jpg\"\r\n");
      out.write("								class=\"card-img-top\" alt=\"...\" />\r\n");
      out.write("							<div class=\"card-body\">\r\n");
      out.write("								<h5 class=\"card-title\">Hôn nhau có gây xùi mào gà không?\r\n");
      out.write("									Bốn cách phòng bệnh</h5>\r\n");
      out.write("								<p class=\"card-text\">Nhiều cặp đôi thắc mắc là khi hôn nhau\r\n");
      out.write("									có lây sùi mào gà không? Hôn nhau được xem là một cách truyền\r\n");
      out.write("									tải tình cảm, mang đến cảm giác hưng phân cho các cặp đôi. Vậy\r\n");
      out.write("									khi có lây sùi mào gà không? Bệnh sùi mào gà có lây qua đường\r\n");
      out.write("									miệng không? Hãy theo dõi bài viết sau đây để giải đáp các thắc\r\n");
      out.write("									mắc trên.</p>\r\n");
      out.write("								<small class=\"viewer\"> <span>10/10/2024</span>\r\n");
      out.write("									<div>\r\n");
      out.write("										<svg width=\"15\" height=\"11\" viewBox=\"0 0 15 11\" fill=\"none\"\r\n");
      out.write("											class=\"icon-color\" xmlns=\"http://www.w3.org/2000/svg\">\r\n");
      out.write("                        <path\r\n");
      out.write("												d=\"M14.9698 5.33C14.3817 3.80882 13.3608 2.49331 12.0332 1.54604C10.7056 0.598778 9.12953 0.0612865 7.49979 0C5.87005 0.0612865 4.29398 0.598778 2.96639 1.54604C1.6388 2.49331 0.617868 3.80882 0.0297873 5.33C-0.00992909 5.43985 -0.00992909 5.56015 0.0297873 5.67C0.617868 7.19118 1.6388 8.50669 2.96639 9.45396C4.29398 10.4012 5.87005 10.9387 7.49979 11C9.12953 10.9387 10.7056 10.4012 12.0332 9.45396C13.3608 8.50669 14.3817 7.19118 14.9698 5.67C15.0095 5.56015 15.0095 5.43985 14.9698 5.33ZM7.49979 10C4.84979 10 2.04979 8.035 1.03479 5.5C2.04979 2.965 4.84979 1 7.49979 1C10.1498 1 12.9498 2.965 13.9648 5.5C12.9498 8.035 10.1498 10 7.49979 10Z\"\r\n");
      out.write("												fill=\"#005594\"></path>\r\n");
      out.write("                        <path\r\n");
      out.write("												d=\"M7.49976 2.5C6.90641 2.5 6.32639 2.67595 5.83305 3.00559C5.3397 3.33524 4.95518 3.80377 4.72812 4.35195C4.50106 4.90013 4.44165 5.50333 4.5574 6.08527C4.67316 6.66721 4.95888 7.20176 5.37844 7.62132C5.79799 8.04088 6.33254 8.3266 6.91449 8.44236C7.49643 8.55811 8.09963 8.4987 8.64781 8.27164C9.19599 8.04458 9.66452 7.66006 9.99417 7.16671C10.3238 6.67336 10.4998 6.09334 10.4998 5.5C10.4998 4.70435 10.1837 3.94129 9.62108 3.37868C9.05847 2.81607 8.29541 2.5 7.49976 2.5ZM7.49976 7.5C7.10419 7.5 6.71751 7.3827 6.38862 7.16294C6.05972 6.94318 5.80337 6.63082 5.652 6.26537C5.50062 5.89991 5.46102 5.49778 5.53819 5.10982C5.61536 4.72186 5.80584 4.36549 6.08554 4.08579C6.36525 3.80608 6.72161 3.6156 7.10958 3.53843C7.49754 3.46126 7.89967 3.50087 8.26512 3.65224C8.63058 3.80362 8.94293 4.05996 9.1627 4.38886C9.38246 4.71776 9.49976 5.10444 9.49976 5.5C9.49976 6.03043 9.28904 6.53914 8.91397 6.91421C8.5389 7.28929 8.03019 7.5 7.49976 7.5Z\"\r\n");
      out.write("												fill=\"#005594\"></path>\r\n");
      out.write("                      </svg>\r\n");
      out.write("										<span>500</span>\r\n");
      out.write("									</div>\r\n");
      out.write("								</small>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- cart -->\r\n");
      out.write("						<div class=\"card\"\r\n");
      out.write("							onclick=\"window.location.href='../listCamNang/cart1.html'\"\r\n");
      out.write("							style=\"cursor: pointer\">\r\n");
      out.write("							<img src=\"img/hon-nhau-co-lay-sui-mao-ga-khong-1.jpg\"\r\n");
      out.write("								class=\"card-img-top\" alt=\"...\" />\r\n");
      out.write("							<div class=\"card-body\">\r\n");
      out.write("								<h5 class=\"card-title\">Hôn nhau có gây xùi mào gà không?\r\n");
      out.write("									Bốn cách phòng bệnh</h5>\r\n");
      out.write("								<p class=\"card-text\">Nhiều cặp đôi thắc mắc là khi hôn nhau\r\n");
      out.write("									có lây sùi mào gà không? Hôn nhau được xem là một cách truyền\r\n");
      out.write("									tải tình cảm, mang đến cảm giác hưng phân cho các cặp đôi. Vậy\r\n");
      out.write("									khi có lây sùi mào gà không? Bệnh sùi mào gà có lây qua đường\r\n");
      out.write("									miệng không? Hãy theo dõi bài viết sau đây để giải đáp các thắc\r\n");
      out.write("									mắc trên.</p>\r\n");
      out.write("								<small class=\"viewer\"> <span>10/10/2024</span>\r\n");
      out.write("									<div>\r\n");
      out.write("										<svg width=\"15\" height=\"11\" viewBox=\"0 0 15 11\" fill=\"none\"\r\n");
      out.write("											class=\"icon-color\" xmlns=\"http://www.w3.org/2000/svg\">\r\n");
      out.write("                        <path\r\n");
      out.write("												d=\"M14.9698 5.33C14.3817 3.80882 13.3608 2.49331 12.0332 1.54604C10.7056 0.598778 9.12953 0.0612865 7.49979 0C5.87005 0.0612865 4.29398 0.598778 2.96639 1.54604C1.6388 2.49331 0.617868 3.80882 0.0297873 5.33C-0.00992909 5.43985 -0.00992909 5.56015 0.0297873 5.67C0.617868 7.19118 1.6388 8.50669 2.96639 9.45396C4.29398 10.4012 5.87005 10.9387 7.49979 11C9.12953 10.9387 10.7056 10.4012 12.0332 9.45396C13.3608 8.50669 14.3817 7.19118 14.9698 5.67C15.0095 5.56015 15.0095 5.43985 14.9698 5.33ZM7.49979 10C4.84979 10 2.04979 8.035 1.03479 5.5C2.04979 2.965 4.84979 1 7.49979 1C10.1498 1 12.9498 2.965 13.9648 5.5C12.9498 8.035 10.1498 10 7.49979 10Z\"\r\n");
      out.write("												fill=\"#005594\"></path>\r\n");
      out.write("                        <path\r\n");
      out.write("												d=\"M7.49976 2.5C6.90641 2.5 6.32639 2.67595 5.83305 3.00559C5.3397 3.33524 4.95518 3.80377 4.72812 4.35195C4.50106 4.90013 4.44165 5.50333 4.5574 6.08527C4.67316 6.66721 4.95888 7.20176 5.37844 7.62132C5.79799 8.04088 6.33254 8.3266 6.91449 8.44236C7.49643 8.55811 8.09963 8.4987 8.64781 8.27164C9.19599 8.04458 9.66452 7.66006 9.99417 7.16671C10.3238 6.67336 10.4998 6.09334 10.4998 5.5C10.4998 4.70435 10.1837 3.94129 9.62108 3.37868C9.05847 2.81607 8.29541 2.5 7.49976 2.5ZM7.49976 7.5C7.10419 7.5 6.71751 7.3827 6.38862 7.16294C6.05972 6.94318 5.80337 6.63082 5.652 6.26537C5.50062 5.89991 5.46102 5.49778 5.53819 5.10982C5.61536 4.72186 5.80584 4.36549 6.08554 4.08579C6.36525 3.80608 6.72161 3.6156 7.10958 3.53843C7.49754 3.46126 7.89967 3.50087 8.26512 3.65224C8.63058 3.80362 8.94293 4.05996 9.1627 4.38886C9.38246 4.71776 9.49976 5.10444 9.49976 5.5C9.49976 6.03043 9.28904 6.53914 8.91397 6.91421C8.5389 7.28929 8.03019 7.5 7.49976 7.5Z\"\r\n");
      out.write("												fill=\"#005594\"></path>\r\n");
      out.write("                      </svg>\r\n");
      out.write("										<span>500</span>\r\n");
      out.write("									</div>\r\n");
      out.write("								</small>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- cart -->\r\n");
      out.write("						<div class=\"card\"\r\n");
      out.write("							onclick=\"window.location.href='../listCamNang/cart1.html'\"\r\n");
      out.write("							style=\"cursor: pointer\">\r\n");
      out.write("							<img src=\"img/hon-nhau-co-lay-sui-mao-ga-khong-1.jpg\"\r\n");
      out.write("								class=\"card-img-top\" alt=\"...\" />\r\n");
      out.write("							<div class=\"card-body\">\r\n");
      out.write("								<h5 class=\"card-title\">Hôn nhau có gây xùi mào gà không?\r\n");
      out.write("									Bốn cách phòng bệnh</h5>\r\n");
      out.write("								<p class=\"card-text\">Nhiều cặp đôi thắc mắc là khi hôn nhau\r\n");
      out.write("									có lây sùi mào gà không? Hôn nhau được xem là một cách truyền\r\n");
      out.write("									tải tình cảm, mang đến cảm giác hưng phân cho các cặp đôi. Vậy\r\n");
      out.write("									khi có lây sùi mào gà không? Bệnh sùi mào gà có lây qua đường\r\n");
      out.write("									miệng không? Hãy theo dõi bài viết sau đây để giải đáp các thắc\r\n");
      out.write("									mắc trên.</p>\r\n");
      out.write("								<small class=\"viewer\"> <span>10/10/2024</span>\r\n");
      out.write("									<div>\r\n");
      out.write("										<svg width=\"15\" height=\"11\" viewBox=\"0 0 15 11\" fill=\"none\"\r\n");
      out.write("											class=\"icon-color\" xmlns=\"http://www.w3.org/2000/svg\">\r\n");
      out.write("                        <path\r\n");
      out.write("												d=\"M14.9698 5.33C14.3817 3.80882 13.3608 2.49331 12.0332 1.54604C10.7056 0.598778 9.12953 0.0612865 7.49979 0C5.87005 0.0612865 4.29398 0.598778 2.96639 1.54604C1.6388 2.49331 0.617868 3.80882 0.0297873 5.33C-0.00992909 5.43985 -0.00992909 5.56015 0.0297873 5.67C0.617868 7.19118 1.6388 8.50669 2.96639 9.45396C4.29398 10.4012 5.87005 10.9387 7.49979 11C9.12953 10.9387 10.7056 10.4012 12.0332 9.45396C13.3608 8.50669 14.3817 7.19118 14.9698 5.67C15.0095 5.56015 15.0095 5.43985 14.9698 5.33ZM7.49979 10C4.84979 10 2.04979 8.035 1.03479 5.5C2.04979 2.965 4.84979 1 7.49979 1C10.1498 1 12.9498 2.965 13.9648 5.5C12.9498 8.035 10.1498 10 7.49979 10Z\"\r\n");
      out.write("												fill=\"#005594\"></path>\r\n");
      out.write("                        <path\r\n");
      out.write("												d=\"M7.49976 2.5C6.90641 2.5 6.32639 2.67595 5.83305 3.00559C5.3397 3.33524 4.95518 3.80377 4.72812 4.35195C4.50106 4.90013 4.44165 5.50333 4.5574 6.08527C4.67316 6.66721 4.95888 7.20176 5.37844 7.62132C5.79799 8.04088 6.33254 8.3266 6.91449 8.44236C7.49643 8.55811 8.09963 8.4987 8.64781 8.27164C9.19599 8.04458 9.66452 7.66006 9.99417 7.16671C10.3238 6.67336 10.4998 6.09334 10.4998 5.5C10.4998 4.70435 10.1837 3.94129 9.62108 3.37868C9.05847 2.81607 8.29541 2.5 7.49976 2.5ZM7.49976 7.5C7.10419 7.5 6.71751 7.3827 6.38862 7.16294C6.05972 6.94318 5.80337 6.63082 5.652 6.26537C5.50062 5.89991 5.46102 5.49778 5.53819 5.10982C5.61536 4.72186 5.80584 4.36549 6.08554 4.08579C6.36525 3.80608 6.72161 3.6156 7.10958 3.53843C7.49754 3.46126 7.89967 3.50087 8.26512 3.65224C8.63058 3.80362 8.94293 4.05996 9.1627 4.38886C9.38246 4.71776 9.49976 5.10444 9.49976 5.5C9.49976 6.03043 9.28904 6.53914 8.91397 6.91421C8.5389 7.28929 8.03019 7.5 7.49976 7.5Z\"\r\n");
      out.write("												fill=\"#005594\"></path>\r\n");
      out.write("                      </svg>\r\n");
      out.write("										<span>500</span>\r\n");
      out.write("									</div>\r\n");
      out.write("								</small>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- cart -->\r\n");
      out.write("						<div class=\"card\"\r\n");
      out.write("							onclick=\"window.location.href='../listCamNang/cart1.html'\"\r\n");
      out.write("							style=\"cursor: pointer\">\r\n");
      out.write("							<img src=\"img/hon-nhau-co-lay-sui-mao-ga-khong-1.jpg\"\r\n");
      out.write("								class=\"card-img-top\" alt=\"...\" />\r\n");
      out.write("							<div class=\"card-body\">\r\n");
      out.write("								<h5 class=\"card-title\">Hôn nhau có gây xùi mào gà không?\r\n");
      out.write("									Bốn cách phòng bệnh</h5>\r\n");
      out.write("								<p class=\"card-text\">Nhiều cặp đôi thắc mắc là khi hôn nhau\r\n");
      out.write("									có lây sùi mào gà không? Hôn nhau được xem là một cách truyền\r\n");
      out.write("									tải tình cảm, mang đến cảm giác hưng phân cho các cặp đôi. Vậy\r\n");
      out.write("									khi có lây sùi mào gà không? Bệnh sùi mào gà có lây qua đường\r\n");
      out.write("									miệng không? Hãy theo dõi bài viết sau đây để giải đáp các thắc\r\n");
      out.write("									mắc trên.</p>\r\n");
      out.write("								<small class=\"viewer\"> <span>10/10/2024</span>\r\n");
      out.write("									<div>\r\n");
      out.write("										<svg width=\"15\" height=\"11\" viewBox=\"0 0 15 11\" fill=\"none\"\r\n");
      out.write("											class=\"icon-color\" xmlns=\"http://www.w3.org/2000/svg\">\r\n");
      out.write("                        <path\r\n");
      out.write("												d=\"M14.9698 5.33C14.3817 3.80882 13.3608 2.49331 12.0332 1.54604C10.7056 0.598778 9.12953 0.0612865 7.49979 0C5.87005 0.0612865 4.29398 0.598778 2.96639 1.54604C1.6388 2.49331 0.617868 3.80882 0.0297873 5.33C-0.00992909 5.43985 -0.00992909 5.56015 0.0297873 5.67C0.617868 7.19118 1.6388 8.50669 2.96639 9.45396C4.29398 10.4012 5.87005 10.9387 7.49979 11C9.12953 10.9387 10.7056 10.4012 12.0332 9.45396C13.3608 8.50669 14.3817 7.19118 14.9698 5.67C15.0095 5.56015 15.0095 5.43985 14.9698 5.33ZM7.49979 10C4.84979 10 2.04979 8.035 1.03479 5.5C2.04979 2.965 4.84979 1 7.49979 1C10.1498 1 12.9498 2.965 13.9648 5.5C12.9498 8.035 10.1498 10 7.49979 10Z\"\r\n");
      out.write("												fill=\"#005594\"></path>\r\n");
      out.write("                        <path\r\n");
      out.write("												d=\"M7.49976 2.5C6.90641 2.5 6.32639 2.67595 5.83305 3.00559C5.3397 3.33524 4.95518 3.80377 4.72812 4.35195C4.50106 4.90013 4.44165 5.50333 4.5574 6.08527C4.67316 6.66721 4.95888 7.20176 5.37844 7.62132C5.79799 8.04088 6.33254 8.3266 6.91449 8.44236C7.49643 8.55811 8.09963 8.4987 8.64781 8.27164C9.19599 8.04458 9.66452 7.66006 9.99417 7.16671C10.3238 6.67336 10.4998 6.09334 10.4998 5.5C10.4998 4.70435 10.1837 3.94129 9.62108 3.37868C9.05847 2.81607 8.29541 2.5 7.49976 2.5ZM7.49976 7.5C7.10419 7.5 6.71751 7.3827 6.38862 7.16294C6.05972 6.94318 5.80337 6.63082 5.652 6.26537C5.50062 5.89991 5.46102 5.49778 5.53819 5.10982C5.61536 4.72186 5.80584 4.36549 6.08554 4.08579C6.36525 3.80608 6.72161 3.6156 7.10958 3.53843C7.49754 3.46126 7.89967 3.50087 8.26512 3.65224C8.63058 3.80362 8.94293 4.05996 9.1627 4.38886C9.38246 4.71776 9.49976 5.10444 9.49976 5.5C9.49976 6.03043 9.28904 6.53914 8.91397 6.91421C8.5389 7.28929 8.03019 7.5 7.49976 7.5Z\"\r\n");
      out.write("												fill=\"#005594\"></path>\r\n");
      out.write("                      </svg>\r\n");
      out.write("										<span>500</span>\r\n");
      out.write("									</div>\r\n");
      out.write("								</small>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- cart -->\r\n");
      out.write("						<div class=\"card\"\r\n");
      out.write("							onclick=\"window.location.href='../listCamNang/cart1.html'\"\r\n");
      out.write("							style=\"cursor: pointer\">\r\n");
      out.write("							<img src=\"img/hon-nhau-co-lay-sui-mao-ga-khong-1.jpg\"\r\n");
      out.write("								class=\"card-img-top\" alt=\"...\" />\r\n");
      out.write("							<div class=\"card-body\">\r\n");
      out.write("								<h5 class=\"card-title\">Hôn nhau có gây xùi mào gà không?\r\n");
      out.write("									Bốn cách phòng bệnh</h5>\r\n");
      out.write("								<p class=\"card-text\">Nhiều cặp đôi thắc mắc là khi hôn nhau\r\n");
      out.write("									có lây sùi mào gà không? Hôn nhau được xem là một cách truyền\r\n");
      out.write("									tải tình cảm, mang đến cảm giác hưng phân cho các cặp đôi. Vậy\r\n");
      out.write("									khi có lây sùi mào gà không? Bệnh sùi mào gà có lây qua đường\r\n");
      out.write("									miệng không? Hãy theo dõi bài viết sau đây để giải đáp các thắc\r\n");
      out.write("									mắc trên.</p>\r\n");
      out.write("								<small class=\"viewer\"> <span>10/10/2024</span>\r\n");
      out.write("									<div>\r\n");
      out.write("										<svg width=\"15\" height=\"11\" viewBox=\"0 0 15 11\" fill=\"none\"\r\n");
      out.write("											class=\"icon-color\" xmlns=\"http://www.w3.org/2000/svg\">\r\n");
      out.write("                        <path\r\n");
      out.write("												d=\"M14.9698 5.33C14.3817 3.80882 13.3608 2.49331 12.0332 1.54604C10.7056 0.598778 9.12953 0.0612865 7.49979 0C5.87005 0.0612865 4.29398 0.598778 2.96639 1.54604C1.6388 2.49331 0.617868 3.80882 0.0297873 5.33C-0.00992909 5.43985 -0.00992909 5.56015 0.0297873 5.67C0.617868 7.19118 1.6388 8.50669 2.96639 9.45396C4.29398 10.4012 5.87005 10.9387 7.49979 11C9.12953 10.9387 10.7056 10.4012 12.0332 9.45396C13.3608 8.50669 14.3817 7.19118 14.9698 5.67C15.0095 5.56015 15.0095 5.43985 14.9698 5.33ZM7.49979 10C4.84979 10 2.04979 8.035 1.03479 5.5C2.04979 2.965 4.84979 1 7.49979 1C10.1498 1 12.9498 2.965 13.9648 5.5C12.9498 8.035 10.1498 10 7.49979 10Z\"\r\n");
      out.write("												fill=\"#005594\"></path>\r\n");
      out.write("                        <path\r\n");
      out.write("												d=\"M7.49976 2.5C6.90641 2.5 6.32639 2.67595 5.83305 3.00559C5.3397 3.33524 4.95518 3.80377 4.72812 4.35195C4.50106 4.90013 4.44165 5.50333 4.5574 6.08527C4.67316 6.66721 4.95888 7.20176 5.37844 7.62132C5.79799 8.04088 6.33254 8.3266 6.91449 8.44236C7.49643 8.55811 8.09963 8.4987 8.64781 8.27164C9.19599 8.04458 9.66452 7.66006 9.99417 7.16671C10.3238 6.67336 10.4998 6.09334 10.4998 5.5C10.4998 4.70435 10.1837 3.94129 9.62108 3.37868C9.05847 2.81607 8.29541 2.5 7.49976 2.5ZM7.49976 7.5C7.10419 7.5 6.71751 7.3827 6.38862 7.16294C6.05972 6.94318 5.80337 6.63082 5.652 6.26537C5.50062 5.89991 5.46102 5.49778 5.53819 5.10982C5.61536 4.72186 5.80584 4.36549 6.08554 4.08579C6.36525 3.80608 6.72161 3.6156 7.10958 3.53843C7.49754 3.46126 7.89967 3.50087 8.26512 3.65224C8.63058 3.80362 8.94293 4.05996 9.1627 4.38886C9.38246 4.71776 9.49976 5.10444 9.49976 5.5C9.49976 6.03043 9.28904 6.53914 8.91397 6.91421C8.5389 7.28929 8.03019 7.5 7.49976 7.5Z\"\r\n");
      out.write("												fill=\"#005594\"></path>\r\n");
      out.write("                      </svg>\r\n");
      out.write("										<span>500</span>\r\n");
      out.write("									</div>\r\n");
      out.write("								</small>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- Cột bên phải -->\r\n");
      out.write("				<div class=\"main-right col-xl-2 col-lg-4 col-md-5 col-sm-12\">\r\n");
      out.write("					<div class=\"main-right-list\">\r\n");
      out.write("						<div class=\"d-flex main-right-title\">\r\n");
      out.write("							<h6 class=\"text-red\">Chuyên khoa</h6>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"list-a\">\r\n");
      out.write("							<ul class=\"list-group\">\r\n");
      out.write("								<li class=\"list-group-item\"><a href=\"#\">Nhi</a></li>\r\n");
      out.write("								<li class=\"list-group-item\"><a href=\"#\">Phụ sản</a></li>\r\n");
      out.write("								<li class=\"list-group-item\"><a href=\"#\">Da liễu</a></li>\r\n");
      out.write("								<li class=\"list-group-item\"><a href=\"#\">Tâm Lý</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- footer -->\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("<title>Footer Example</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/footer.css\" />\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/bootstrap/bootstrap.min.css\" />\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css\"\r\n");
      out.write("	rel=\"stylesheet\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- Footer -->\r\n");
      out.write("	<footer class=\"container-fluid\">\r\n");
      out.write("		<!-- Logo and Social Icons Container -->\r\n");
      out.write("		<div class=\"footer-logo-icons\">\r\n");
      out.write("			<div class=\"footer-logo\">\r\n");
      out.write("				<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/logoP.png\" alt=\"Logo\" />\r\n");
      out.write("				<h2>WHM - Women's Health Maternity</h2>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- Phần Icon -->\r\n");
      out.write("			<div class=\"social-icons d-flex\">\r\n");
      out.write("				<a href=\"#\" class=\"me-4 text-reset\"> <i class=\"bi bi-facebook\"></i>\r\n");
      out.write("				</a> <a href=\"#\" class=\"me-4 text-reset\"> <i class=\"bi bi-instagram\"></i>\r\n");
      out.write("				</a> <a href=\"#\" class=\"me-4 text-reset\"> <i class=\"bi bi-whatsapp\"></i>\r\n");
      out.write("				</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- Section: Links -->\r\n");
      out.write("		<section class=\"footer-links\">\r\n");
      out.write("			<div class=\"row justify-content-between\">\r\n");
      out.write("				<!-- Contact Info -->\r\n");
      out.write("				<div class=\"col-md-3 col-lg-3 col-xl-3 mx-auto mb-4\">\r\n");
      out.write("					<h4 class=\"text-uppercase fw-bold mb-4\">Thông tin liên hệ</h4>\r\n");
      out.write("					<p>\r\n");
      out.write("						<i class=\"bi bi-geo-alt\"></i>Khoa Công Nghệ Thông Tin, Trường Đại\r\n");
      out.write("						Học Nông Lâm TP.Hồ Chí Minh\r\n");
      out.write("					</p>\r\n");
      out.write("					<p>\r\n");
      out.write("						<i class=\"bi bi-envelope-at\"></i> 22130078@st.hcmuaf.edu.vn<br>\r\n");
      out.write("						<i class=\"bi bi-envelope-at\"></i> 22130262@st.hcmuaf.edu.vn\r\n");
      out.write("					</p>\r\n");
      out.write("					</p>\r\n");
      out.write("					<p>\r\n");
      out.write("						<i class=\"bi bi-telephone\"></i>1808 1309\r\n");
      out.write("					</p>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<!-- Services -->\r\n");
      out.write("				<div class=\"col-md-2 col-lg-2 col-xl-2 mx-auto mb-4\">\r\n");
      out.write("					<h4 class=\"text-uppercase fw-bold mb-4\">Dịch vụ</h4>\r\n");
      out.write("					<p>\r\n");
      out.write("						<a href=\"#\" class=\"text-reset\">Đặt lịch khám</a>\r\n");
      out.write("					</p>\r\n");
      out.write("					<p>\r\n");
      out.write("						<a href=\"#\" class=\"text-reset\">Hỏi đáp bác sĩ</a>\r\n");
      out.write("					</p>\r\n");
      out.write("					<p>\r\n");
      out.write("						<a href=\"#\" class=\"text-reset\">Hồ sơ sức khỏe</a>\r\n");
      out.write("					</p>\r\n");
      out.write("					<p>\r\n");
      out.write("						<a href=\"#\" class=\"text-reset\">Cẩm nang y tế</a>\r\n");
      out.write("					</p>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<!-- Policies -->\r\n");
      out.write("				<div class=\"col-md-3 col-lg-2 col-xl-2 mx-auto mb-4\">\r\n");
      out.write("					<h4 class=\"text-uppercase fw-bold mb-4\">Chính sách</h4>\r\n");
      out.write("					<p>\r\n");
      out.write("						<a href=\"#\" class=\"text-reset\">Điều khoản sử dụng</a>\r\n");
      out.write("					</p>\r\n");
      out.write("					<p>\r\n");
      out.write("						<a href=\"#\" class=\"text-reset\">Chính sách bảo mật</a>\r\n");
      out.write("					</p>\r\n");
      out.write("					<p>\r\n");
      out.write("						<a href=\"#\" class=\"text-reset\">Quy chế hoạt động</a>\r\n");
      out.write("					</p>\r\n");
      out.write("					<p>\r\n");
      out.write("						<a href=\"#\" class=\"text-reset\">Trung tâm trợ giúp</a>\r\n");
      out.write("					</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</section>\r\n");
      out.write("		<!-- Section: Links -->\r\n");
      out.write("\r\n");
      out.write("		<!-- Copyright -->\r\n");
      out.write("		<div class=\"text-center p-4\">&copy; 2024 WHM - Women's Health\r\n");
      out.write("			Maternity. All rights reserved.</div>\r\n");
      out.write("		<!-- Copyright -->\r\n");
      out.write("	</footer>\r\n");
      out.write("	<!-- Footer -->\r\n");
      out.write("	<script src=\"../../bootstrap/bootstrap.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/bootstrap/bootstrap.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/bootstrap/bootstrap.bundle.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
