/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.31
 * Generated at: 2025-01-07 16:49:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class QaA_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/view/ViewShare/header.jsp", Long.valueOf(1736268515856L));
    _jspx_dependants.put("/view/ViewShare/footer.jsp", Long.valueOf(1736255848937L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("<title>Hỏi đáp Bác Sĩ</title>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/bootstrap/bootstrap.min.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/QaA.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/style.css\" />\r\n");
      out.write("\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css\"\r\n");
      out.write("	rel=\"stylesheet\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- header -->\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<title>Header</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/header.css\" />\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/bootstrap/bootstrap.min.css\" />\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!--header start-->\r\n");
      out.write("	<header class=\"header\">\r\n");
      out.write("		<div class=\"headerTop\">\r\n");
      out.write("			<div\r\n");
      out.write("				class=\"container d-flex justify-content-between align-items-center\">\r\n");
      out.write("				<div class=\"hotline\">\r\n");
      out.write("					Hotline Tư vấn:\r\n");
      out.write("					<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\"\r\n");
      out.write("						fill=\"currentColor\" class=\"bi bi-telephone-fill\"\r\n");
      out.write("						viewBox=\"0 0 16 16\">\r\n");
      out.write("              <path fill-rule=\"evenodd\"\r\n");
      out.write("							d=\"M1.885.511a1.745 1.745 0 0 1 2.61.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.68.68 0 0 0 .178.643l2.457 2.457a.68.68 0 0 0 .644.178l2.189-.547a1.75 1.75 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.6 18.6 0 0 1-7.01-4.42 18.6 18.6 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877z\" />\r\n");
      out.write("            </svg>\r\n");
      out.write("					1808 1309\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"login d-flex align-items-center position-relative\">\r\n");
      out.write("					<span class=\"name\">Subeo dangiu</span>\r\n");
      out.write("					<li class=\"nav-item dropdown\"><i class=\"bi bi-person-circle\"></i>\r\n");
      out.write("						<ul class=\"dropdown-menu\">\r\n");
      out.write("							<li><a class=\"dropdown-item\"\r\n");
      out.write("								href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/view/Login.jsp\"><i\r\n");
      out.write("									class=\"bi bi-box-arrow-right\"></i> Đăng xuất </a></li>\r\n");
      out.write("						</ul></li>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!--navbar start-->\r\n");
      out.write("		<nav class=\"navbar navbar-expand-lg\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"row w-100 align-items-center\">\r\n");
      out.write("					<div class=\"col-lg-3 col-md-4 col-sm-6\">\r\n");
      out.write("						<a class=\"navbar-brand text-pink\"\r\n");
      out.write("							href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/view/homepage.jsp\">\r\n");
      out.write("							<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/logoWHM.png\"\r\n");
      out.write("							alt=\"Women's Health Maternity\" />\r\n");
      out.write("						</a>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-lg-9 col-md-8 col-sm-6\">\r\n");
      out.write("						<button class=\"navbar-toggler\" type=\"button\"\r\n");
      out.write("							data-bs-toggle=\"collapse\" data-bs-target=\"#navbarNav\"\r\n");
      out.write("							aria-controls=\"navbarNav\" aria-expanded=\"false\"\r\n");
      out.write("							aria-label=\"Toggle navigation\">\r\n");
      out.write("							<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("						</button>\r\n");
      out.write("						<div class=\"collapse navbar-collapse\" id=\"navbarNav\">\r\n");
      out.write("							<ul class=\"navbar-nav ms-auto\">\r\n");
      out.write("								<!-- đặt khám -->\r\n");
      out.write("								<li class=\"nav-item dropdown\"><a\r\n");
      out.write("									class=\"nav-link dropdown-toggle\" href=\"#\" id=\"bookingDropdown\"\r\n");
      out.write("									role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("										Đặt lịch khám </a>\r\n");
      out.write("									<ul class=\"dropdown-menu\" aria-labelledby=\"bookingDropdown\">\r\n");
      out.write("										<li><a class=\"dropdown-item\"\r\n");
      out.write("											href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/bookingDoctor\">Bác\r\n");
      out.write("												Sĩ</a></li>\r\n");
      out.write("										<li><a class=\"dropdown-item\"\r\n");
      out.write("											href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/bookingMedilFaci\">Cơ\r\n");
      out.write("												sở y tế</a></li>\r\n");
      out.write("									</ul></li>\r\n");
      out.write("								<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("									href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/QaA\">Hỏi đáp bác\r\n");
      out.write("										sĩ</a></li>\r\n");
      out.write("								<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("									href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/healthRecord\">Hồ\r\n");
      out.write("										sơ sức khỏe</a></li>\r\n");
      out.write("								<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("									href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/handbook\">Cẩm nang</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</nav>\r\n");
      out.write("		<!--navbar end-->\r\n");
      out.write("	</header>\r\n");
      out.write("	<!--header end-->\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/bootstrap/bootstrap.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("	<!-- body -->\r\n");
      out.write("	<!-- search -->\r\n");
      out.write("	<div class=\"mb-3 mb-md-4\">\r\n");
      out.write("		<div class=\"container-fluid\">\r\n");
      out.write("			<div class=\"panel-search\">\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("					<div class=\"col-12 text-center\">\r\n");
      out.write("						<h1 class=\"text-red\">Hỏi đáp miễn phí với Bác sĩ</h1>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"row justify-content-center\">\r\n");
      out.write("					<div class=\"col-12 col-sm-11 col-md-10 col-lg-10 col-xl-9\">\r\n");
      out.write("						<!-- search -->\r\n");
      out.write("						<div class=\"input-btn\">\r\n");
      out.write("							<span class=\"custom-input-group-text\"> <i\r\n");
      out.write("								class=\"bi bi-search\"></i>\r\n");
      out.write("							</span> <input type=\"search\" class=\"custom-input\"\r\n");
      out.write("								placeholder=\"Tìm kiếm chủ đề...\" aria-label=\"Tìm kiếm chủ đề\" />\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"container\">\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("						<div class=\"col-12 position-relative\">\r\n");
      out.write("							<div class=\"d-flex flex-wrap topics\">\r\n");
      out.write("								<button type=\"button\"\r\n");
      out.write("									class=\"btn btn-md m-1 font-weight-bold topic\">\r\n");
      out.write("									<a href=\"/cong-dong/Ho-hap-1\">Hô hấp</a>\r\n");
      out.write("								</button>\r\n");
      out.write("								<button type=\"button\"\r\n");
      out.write("									class=\"btn btn-md m-1 font-weight-bold active topic\">\r\n");
      out.write("									<a href=\"/cong-dong/Chuyen-khoa-Noi-khoa-2\">Chuyên\r\n");
      out.write("										khoa Nội khoa</a>\r\n");
      out.write("								</button>\r\n");
      out.write("								<button type=\"button\"\r\n");
      out.write("									class=\"btn btn-md m-1 font-weight-bold topic\">\r\n");
      out.write("									<a\r\n");
      out.write("										href=\"/cong-dong/TT-Phau-Thuat-dai-truc-trang-Tang-sinh-mon-3\">Chuyên\r\n");
      out.write("										khoa da liễu</a>\r\n");
      out.write("								</button>\r\n");
      out.write("								<button type=\"button\"\r\n");
      out.write("									class=\"btn btn-md m-1 font-weight-bold topic\">\r\n");
      out.write("									<a href=\"/cong-dong/Chuyen-khoa-San-4\">Chuyên khoa Sản</a>\r\n");
      out.write("								</button>\r\n");
      out.write("								<button type=\"button\"\r\n");
      out.write("									class=\"btn btn-md m-1 font-weight-bold topic\">\r\n");
      out.write("									<a href=\"/cong-dong/Chuyen-khoa-Noi-nhi-5\">Chuyên\r\n");
      out.write("										khoa Nội nhi</a>\r\n");
      out.write("								</button>\r\n");
      out.write("								<button type=\"button\"\r\n");
      out.write("									class=\"btn btn-white btn-md m-1 font-weight-bold topic\">\r\n");
      out.write("									<a href=\"/cong-dong/Chuyen-khoa-Phu-khoa-6\">Chuyên\r\n");
      out.write("										khoa Phụ khoa</a>\r\n");
      out.write("								</button>\r\n");
      out.write("								<button type=\"button\"\r\n");
      out.write("									class=\"btn btn-white btn-md m-1 font-weight-bold topic\">\r\n");
      out.write("									<i class=\"fa fa-th-large mr-2 text-gray2\" aria-hidden=\"true\"></i>Chuyên\r\n");
      out.write("									khoa Tâm Lý\r\n");
      out.write("								</button>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!--  -->\r\n");
      out.write("	<div class=\"container-xl\">\r\n");
      out.write("		<div class=\"row custom-row-spacing\">\r\n");
      out.write("			<!-- hỏi đáp -->\r\n");
      out.write("			<div class=\"d-flex flex-column col-xl-7 col-md-6 gap-3 custom-border\">\r\n");
      out.write("				<!-- test nhan len -->\r\n");
      out.write("				<div class=\"question\">\r\n");
      out.write("					<div class=\"card w-100 cart-style\">\r\n");
      out.write("						<div class=\"card-body\">\r\n");
      out.write("							<h6 class=\"mb-2\">Nữ, 19 tuổi</h6>\r\n");
      out.write("							<p class=\"mb-2 description\">Bác sĩ ơi, cho cháu hỏi mặt cháu\r\n");
      out.write("								hôm qua có 2 đốm đỏ bên trái gần mắt do nước của kiến ba khoang\r\n");
      out.write("								vào, xong đến tối nay thì da mặt vùng bên trái ấy bị tê tê khó\r\n");
      out.write("								chịu thì cháu bị làm sao và phải làm thế nào ạ</p>\r\n");
      out.write("							<div class=\"mb-3 topics\">\r\n");
      out.write("								<button type=\"button\"\r\n");
      out.write("									class=\"btn btn-md m-1 font-weight-bold topic\">\r\n");
      out.write("									<a href=\"\">Chuyên khoa da liễu</a>\r\n");
      out.write("								</button>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"card-icon\">\r\n");
      out.write("								<div class=\"d-flex\">\r\n");
      out.write("									<p>\r\n");
      out.write("										<i class=\"bi bi-clock-history\" aria-hidden=\"true\"></i>19/10/2024\r\n");
      out.write("									</p>\r\n");
      out.write("									<p>\r\n");
      out.write("										<i class=\"bi bi-chat-dots\" aria-hidden=\"true\"></i>1 Trả lời\r\n");
      out.write("									</p>\r\n");
      out.write("									<p>\r\n");
      out.write("										<i class=\"bi bi-heart\" aria-hidden=\"true\"></i>4 Cảm ơn\r\n");
      out.write("									</p>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- test nhan len -->\r\n");
      out.write("					<div class=\"card w-100 cart-style\">\r\n");
      out.write("						<div class=\"card-body\">\r\n");
      out.write("							<h6 class=\"mb-2\">Nữ, 19 tuổi</h6>\r\n");
      out.write("							<p class=\"mb-2 description\">Bác sĩ ơi, cho cháu hỏi mặt cháu\r\n");
      out.write("								hôm qua có 2 đốm đỏ bên trái gần mắt do nước của kiến ba khoang\r\n");
      out.write("								vào, xong đến tối nay thì da mặt vùng bên trái ấy bị tê tê khó\r\n");
      out.write("								chịu thì cháu bị làm sao và phải làm thế nào ạ</p>\r\n");
      out.write("							<div class=\"mb-3 topics\">\r\n");
      out.write("								<button type=\"button\"\r\n");
      out.write("									class=\"btn btn-md m-1 font-weight-bold topic\">\r\n");
      out.write("									<a href=\"\">Chuyên khoa da liễu</a>\r\n");
      out.write("								</button>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"card-icon\">\r\n");
      out.write("								<div class=\"d-flex\">\r\n");
      out.write("									<p>\r\n");
      out.write("										<i class=\"bi bi-clock-history\" aria-hidden=\"true\"></i>19/10/2024\r\n");
      out.write("									</p>\r\n");
      out.write("									<p>\r\n");
      out.write("										<i class=\"bi bi-chat-dots\" aria-hidden=\"true\"></i>1 Trả lời\r\n");
      out.write("									</p>\r\n");
      out.write("									<p>\r\n");
      out.write("										<i class=\"bi bi-heart\" aria-hidden=\"true\"></i>4 Cảm ơn\r\n");
      out.write("									</p>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- test nhan len -->\r\n");
      out.write("					<div class=\"card w-100 cart-style\">\r\n");
      out.write("						<div class=\"card-body\">\r\n");
      out.write("							<h6 class=\"mb-2\">Nữ, 19 tuổi</h6>\r\n");
      out.write("							<p class=\"mb-2 description\">Bác sĩ ơi, cho cháu hỏi mặt cháu\r\n");
      out.write("								hôm qua có 2 đốm đỏ bên trái gần mắt do nước của kiến ba khoang\r\n");
      out.write("								vào, xong đến tối nay thì da mặt vùng bên trái ấy bị tê tê khó\r\n");
      out.write("								chịu thì cháu bị làm sao và phải làm thế nào ạ</p>\r\n");
      out.write("							<div class=\"mb-3 topics\">\r\n");
      out.write("								<button type=\"button\"\r\n");
      out.write("									class=\"btn btn-md m-1 font-weight-bold topic\">\r\n");
      out.write("									<a href=\"\">Chuyên khoa da liễu</a>\r\n");
      out.write("								</button>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"card-icon\">\r\n");
      out.write("								<div class=\"d-flex\">\r\n");
      out.write("									<p>\r\n");
      out.write("										<i class=\"bi bi-clock-history\" aria-hidden=\"true\"></i>19/10/2024\r\n");
      out.write("									</p>\r\n");
      out.write("									<p>\r\n");
      out.write("										<i class=\"bi bi-chat-dots\" aria-hidden=\"true\"></i>1 Trả lời\r\n");
      out.write("									</p>\r\n");
      out.write("									<p>\r\n");
      out.write("										<i class=\"bi bi-heart\" aria-hidden=\"true\"></i>4 Cảm ơn\r\n");
      out.write("									</p>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<!-- test nhan len -->\r\n");
      out.write("					<div class=\"card w-100 cart-style\">\r\n");
      out.write("						<div class=\"card-body\">\r\n");
      out.write("							<h6 class=\"mb-2\">Nữ, 19 tuổi</h6>\r\n");
      out.write("							<p class=\"mb-2 description\">Bác sĩ ơi, cho cháu hỏi mặt cháu\r\n");
      out.write("								hôm qua có 2 đốm đỏ bên trái gần mắt do nước của kiến ba khoang\r\n");
      out.write("								vào, xong đến tối nay thì da mặt vùng bên trái ấy bị tê tê khó\r\n");
      out.write("								chịu thì cháu bị làm sao và phải làm thế nào ạ</p>\r\n");
      out.write("							<div class=\"mb-3 topics\">\r\n");
      out.write("								<button type=\"button\"\r\n");
      out.write("									class=\"btn btn-md m-1 font-weight-bold topic\">\r\n");
      out.write("									<a href=\"\">Chuyên khoa da liễu</a>\r\n");
      out.write("								</button>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"card-icon\">\r\n");
      out.write("								<div class=\"d-flex\">\r\n");
      out.write("									<p>\r\n");
      out.write("										<i class=\"bi bi-clock-history\" aria-hidden=\"true\"></i>19/10/2024\r\n");
      out.write("									</p>\r\n");
      out.write("									<p>\r\n");
      out.write("										<i class=\"bi bi-chat-dots\" aria-hidden=\"true\"></i>1 Trả lời\r\n");
      out.write("									</p>\r\n");
      out.write("									<p>\r\n");
      out.write("										<i class=\"bi bi-heart\" aria-hidden=\"true\"></i>4 Cảm ơn\r\n");
      out.write("									</p>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<!-- Pagination -->\r\n");
      out.write("				<nav aria-label=\"Page navigation\">\r\n");
      out.write("					<ul class=\"pagination\" id=\"pagination\">\r\n");
      out.write("						<li class=\"page-item disabled\" id=\"prev\"><span\r\n");
      out.write("							class=\"page-link\"><<</span></li>\r\n");
      out.write("						<li class=\"page-item active\" id=\"page-1\"><a class=\"page-link\"\r\n");
      out.write("							href=\"#\" onclick=\"changePage(1)\">1</a></li>\r\n");
      out.write("						<li class=\"page-item\" id=\"page-2\"><a class=\"page-link\"\r\n");
      out.write("							href=\"#\" onclick=\"changePage(2)\">2</a></li>\r\n");
      out.write("						<li class=\"page-item\" id=\"page-3\"><a class=\"page-link\"\r\n");
      out.write("							href=\"#\" onclick=\"changePage(3)\">3</a></li>\r\n");
      out.write("						<li class=\"page-item\" id=\"next\"><a class=\"page-link\" href=\"#\"\r\n");
      out.write("							onclick=\"changePage(2)\">>></a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</nav>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- form điền -->\r\n");
      out.write("			<div class=\"col-xl-5 col-lg-4 col-md-3\">\r\n");
      out.write("				<div class=\"form-container right-column\">\r\n");
      out.write("					<h5 class=\"text-red text-center\">ĐẶT CÂU HỎI VỚI BÁC SĨ</h5>\r\n");
      out.write("					<form>\r\n");
      out.write("						<!--  -->\r\n");
      out.write("						<div\r\n");
      out.write("							class=\"d-flex justify-content-between align-items-center mb-3\">\r\n");
      out.write("							<!-- Ảnh đại diện -->\r\n");
      out.write("							<div>\r\n");
      out.write("								<img src=\"/img/Logo.png\" alt=\"Avatar\"\r\n");
      out.write("									style=\"width: 50px; height: 40px; object-fit: cover\" />\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<!-- Chữ \"Tuổi\" và input điền tuổi -->\r\n");
      out.write("							<div class=\"d-flex align-items-center age-input\">\r\n");
      out.write("								<label for=\"age\" style=\"margin-right: 10px\">Tuổi:</label> <input\r\n");
      out.write("									type=\"number\" id=\"age\" name=\"age\" style=\"width: 50px\" min=\"1\"\r\n");
      out.write("									max=\"100\" required />\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<!-- Chọn giới tính -->\r\n");
      out.write("							<div class=\"d-flex align-items-center\">\r\n");
      out.write("								<label> <input type=\"radio\" name=\"gender\" value=\"male\" />\r\n");
      out.write("									Nam\r\n");
      out.write("								</label> <label class=\"ms-2\"> <input type=\"radio\" name=\"gender\"\r\n");
      out.write("									value=\"female\" /> Nữ\r\n");
      out.write("								</label>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"row mb-3\">\r\n");
      out.write("							<div class=\"col\">\r\n");
      out.write("								<div class=\"control-input\">\r\n");
      out.write("									<div class=\"control-input-content\">\r\n");
      out.write("										<div\r\n");
      out.write("											class=\"ant-select ant-select-in-form-item ant-select-multiple ant-select-allow-clear ant-select-show-search\"\r\n");
      out.write("											style=\"width: 100%\">\r\n");
      out.write("											<div class=\"ant-select-selector\">\r\n");
      out.write("												<span class=\"ant-select-selection-placeholder\">Chọn\r\n");
      out.write("													chuyên khoa</span>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<!--  -->\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"mb-3 row\">\r\n");
      out.write("							<div class=\"col-12\">\r\n");
      out.write("								<input maxlength=\"150\"\r\n");
      out.write("									placeholder=\"Tiêu đề (vd: Mọc mụn nước ở lòng bàn tay)\"\r\n");
      out.write("									id=\"title\" class=\"form-control\" type=\"text\" value=\"\"\r\n");
      out.write("									style=\"box-shadow: rgba(0, 0, 0, 0.2) 0px 2px 10px\" />\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"mb-3 row\">\r\n");
      out.write("							<div class=\"col-12\">\r\n");
      out.write("								<textarea rows=\"4\"\r\n");
      out.write("									placeholder=\"Nội dung câu hỏi (vd: Mỗi khi sử dụng hóa chất lòng bàn tay tôi bị đỏ và mọc mụn nước. Nhờ bác sĩ tư vấn cho tôi nên sử dụng thuốc gì?)\"\r\n");
      out.write("									id=\"content\" class=\"form-control\"></textarea>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"group-image mb-3\">\r\n");
      out.write("							<div class=\"picker-image\">\r\n");
      out.write("								<div class=\"button\">\r\n");
      out.write("									<img\r\n");
      out.write("										src=\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAnCAYAAABJ0cukAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAJMSURBVHgB7ZlPUtswFMY/yV60K3KE9AbuDdJFh7IrJ2gy0xkmqw4nIJygsMqk0xnCCWDHhC6anqC9QX2EbLoq9uNJjgIGZMs2ITLDb2fJi+/T09PTHwHFxbiLIDiBoAiEDrxHzJEkA+wMY6HFh/J3O4TnWCBJ30o98u0Tr+go7SFAvVVTSscgOofPBOIjT6Ev2QdFYb6Txb8fzuEzF2NlYmkAHYmWEzr99WPcQ8Khk3ILkub4n/5SKwA8oNiAWV6J80THijhP0EcgY8wm+9je23i+FE+hQJ7lkvyGLgTOdGQ2jN3AbMLZjghFUHCADWM3IB4c+TtQhLqo6ZkNUiPsBohcilu9AqhzS/7U03D2/RMaYDcg6Q/KcfknjxGv8kghkmkTE3YD4espj9ACRRCOUIW74g0NTNgNvBsscJXuW/spPeVl9BSu2MQbapooXkZ3hlPe8b1htWq9X0aDYq4FXAOGfbhSJt5Qw0R5Jc4q7i7q4irekJkAtj87RXe9e6Gq4g0VIrE+A3XFGxxN1DOgi9B4VNjfRLzBwUR1A6siJA9w+e3E2t9UvKHERDUD98RRP2fiscUbRNqzdbmdBxRWcdoE+JbgcC3iS3CLQOnIkjoj/MUTi1eUG1jXtHgkig14Ll5hN9AC8YqC7TRG8Fy8ovXXKi8GNs0zvpnLDix9eM5zm0JiCy1D4HJyew8Tc1MMn7n9DEaIQz6gH3Mcvi67u9zahc9Q7msk8WHviK9IDtE2lGa+1hGrBrX3kTLiw4P/72X/Xp1jd6Cvea4BLCTWvdUImEYAAAAASUVORK5CYII=\"\r\n");
      out.write("										alt=\"\" />\r\n");
      out.write("								</div>\r\n");
      out.write("								<strong>Thêm ảnh</strong><span></span>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"group-image mb-3\">\r\n");
      out.write("							<input multiple type=\"file\" accept=\"image/*\"\r\n");
      out.write("								style=\"display: none\" />\r\n");
      out.write("							<div class=\"attachment\"></div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"text-center text-muted mb-3\">* Câu trả lời của\r\n");
      out.write("							bạn sẽ được hiển thị công khai</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"mb-3 row\">\r\n");
      out.write("							<div class=\"col-12\">\r\n");
      out.write("								<div class=\"d-flex justify-content-center\">\r\n");
      out.write("									<button type=\"submit\" class=\"btn btn-pink btn-lg\">Gửi\r\n");
      out.write("									</button>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- footer -->\r\n");
      out.write("	<!-- footer -->\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("<title>Footer Example</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/footer.css\" />\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/bootstrap/bootstrap.min.css\" />\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css\"\r\n");
      out.write("	rel=\"stylesheet\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- Footer -->\r\n");
      out.write("	<footer class=\"container-fluid\">\r\n");
      out.write("		<!-- Logo and Social Icons Container -->\r\n");
      out.write("		<div class=\"footer-logo-icons\">\r\n");
      out.write("			<div class=\"footer-logo\">\r\n");
      out.write("				<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/logoP.png\" alt=\"Logo\" />\r\n");
      out.write("				<h2>WHM - Women's Health Maternity</h2>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- Phần Icon -->\r\n");
      out.write("			<div class=\"social-icons d-flex\">\r\n");
      out.write("				<a href=\"#\" class=\"me-4 text-reset\"> <i class=\"bi bi-facebook\"></i>\r\n");
      out.write("				</a> <a href=\"#\" class=\"me-4 text-reset\"> <i class=\"bi bi-instagram\"></i>\r\n");
      out.write("				</a> <a href=\"#\" class=\"me-4 text-reset\"> <i class=\"bi bi-whatsapp\"></i>\r\n");
      out.write("				</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- Section: Links -->\r\n");
      out.write("		<section class=\"footer-links\">\r\n");
      out.write("			<div class=\"row justify-content-between\">\r\n");
      out.write("				<!-- Contact Info -->\r\n");
      out.write("				<div class=\"col-md-3 col-lg-3 col-xl-3 mx-auto mb-4\">\r\n");
      out.write("					<h4 class=\"text-uppercase fw-bold mb-4\">Thông tin liên hệ</h4>\r\n");
      out.write("					<p>\r\n");
      out.write("						<i class=\"bi bi-geo-alt\"></i>Khoa Công Nghệ Thông Tin, Trường Đại\r\n");
      out.write("						Học Nông Lâm TP.Hồ Chí Minh\r\n");
      out.write("					</p>\r\n");
      out.write("					<p>\r\n");
      out.write("						<i class=\"bi bi-envelope-at\"></i> 22130078@st.hcmuaf.edu.vn<br>\r\n");
      out.write("						<i class=\"bi bi-envelope-at\"></i> 22130262@st.hcmuaf.edu.vn\r\n");
      out.write("					</p>\r\n");
      out.write("					</p>\r\n");
      out.write("					<p>\r\n");
      out.write("						<i class=\"bi bi-telephone\"></i>1808 1309\r\n");
      out.write("					</p>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<!-- Services -->\r\n");
      out.write("				<div class=\"col-md-2 col-lg-2 col-xl-2 mx-auto mb-4\">\r\n");
      out.write("					<h4 class=\"text-uppercase fw-bold mb-4\">Dịch vụ</h4>\r\n");
      out.write("					<p>\r\n");
      out.write("						<a href=\"#\" class=\"text-reset\">Đặt lịch khám</a>\r\n");
      out.write("					</p>\r\n");
      out.write("					<p>\r\n");
      out.write("						<a href=\"#\" class=\"text-reset\">Hỏi đáp bác sĩ</a>\r\n");
      out.write("					</p>\r\n");
      out.write("					<p>\r\n");
      out.write("						<a href=\"#\" class=\"text-reset\">Hồ sơ sức khỏe</a>\r\n");
      out.write("					</p>\r\n");
      out.write("					<p>\r\n");
      out.write("						<a href=\"#\" class=\"text-reset\">Cẩm nang y tế</a>\r\n");
      out.write("					</p>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<!-- Policies -->\r\n");
      out.write("				<div class=\"col-md-3 col-lg-2 col-xl-2 mx-auto mb-4\">\r\n");
      out.write("					<h4 class=\"text-uppercase fw-bold mb-4\">Chính sách</h4>\r\n");
      out.write("					<p>\r\n");
      out.write("						<a href=\"#\" class=\"text-reset\">Điều khoản sử dụng</a>\r\n");
      out.write("					</p>\r\n");
      out.write("					<p>\r\n");
      out.write("						<a href=\"#\" class=\"text-reset\">Chính sách bảo mật</a>\r\n");
      out.write("					</p>\r\n");
      out.write("					<p>\r\n");
      out.write("						<a href=\"#\" class=\"text-reset\">Quy chế hoạt động</a>\r\n");
      out.write("					</p>\r\n");
      out.write("					<p>\r\n");
      out.write("						<a href=\"#\" class=\"text-reset\">Trung tâm trợ giúp</a>\r\n");
      out.write("					</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</section>\r\n");
      out.write("		<!-- Section: Links -->\r\n");
      out.write("\r\n");
      out.write("		<!-- Copyright -->\r\n");
      out.write("		<div class=\"text-center p-4\">&copy; 2024 WHM - Women's Health\r\n");
      out.write("			Maternity. All rights reserved.</div>\r\n");
      out.write("		<!-- Copyright -->\r\n");
      out.write("	</footer>\r\n");
      out.write("	<!-- Footer -->\r\n");
      out.write("	<script src=\"../../bootstrap/bootstrap.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- script -->\r\n");
      out.write("	<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
