/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.31
 * Generated at: 2025-01-07 13:28:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view.Booking_005fMedical_005fFacility;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class bookingMedical_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/view/ViewShare/header.jsp", Long.valueOf(1736255617638L));
    _jspx_dependants.put("/view/ViewShare/footer.jsp", Long.valueOf(1736255848937L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"UTF-8\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("    <title>Đặt lịch Cơ Sở Y Tế</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../../bootstrap/bootstrap.min.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../../css/bookingMedical.css\" />\r\n");
      out.write("    <link\r\n");
      out.write("      href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css\"\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("    />\r\n");
      out.write("  </head>\r\n");
      out.write("\r\n");
      out.write("  <body>\r\n");
      out.write("    <!-- header -->\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<title>Header</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/header.css\" />\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/bootstrap/bootstrap.min.css\" />\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!--header start-->\r\n");
      out.write("	<header class=\"header\">\r\n");
      out.write("		<div class=\"headerTop\">\r\n");
      out.write("			<div\r\n");
      out.write("				class=\"container d-flex justify-content-between align-items-center\">\r\n");
      out.write("				<div class=\"hotline\">\r\n");
      out.write("					Hotline Tư vấn:\r\n");
      out.write("					<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\"\r\n");
      out.write("						fill=\"currentColor\" class=\"bi bi-telephone-fill\"\r\n");
      out.write("						viewBox=\"0 0 16 16\">\r\n");
      out.write("              <path fill-rule=\"evenodd\"\r\n");
      out.write("							d=\"M1.885.511a1.745 1.745 0 0 1 2.61.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.68.68 0 0 0 .178.643l2.457 2.457a.68.68 0 0 0 .644.178l2.189-.547a1.75 1.75 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.6 18.6 0 0 1-7.01-4.42 18.6 18.6 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877z\" />\r\n");
      out.write("            </svg>\r\n");
      out.write("					1808 1309\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"login d-flex align-items-center position-relative\">\r\n");
      out.write("					<span class=\"name\">Subeo dangiu</span>\r\n");
      out.write("					<li class=\"nav-item dropdown\"><i class=\"bi bi-person-circle\"></i>\r\n");
      out.write("						<ul class=\"dropdown-menu\">\r\n");
      out.write("							<li><a class=\"dropdown-item\"\r\n");
      out.write("								href=\"../DangNhap/dangNhap.html\"><i\r\n");
      out.write("									class=\"bi bi-box-arrow-right\"></i> Đăng xuất </a></li>\r\n");
      out.write("						</ul></li>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!--navbar start-->\r\n");
      out.write("		<nav class=\"navbar navbar-expand-lg\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"row w-100 align-items-center\">\r\n");
      out.write("					<div class=\"col-lg-3 col-md-4 col-sm-6\">\r\n");
      out.write("						<a class=\"navbar-brand text-pink\" href=\"../TrangChu/index.html\">\r\n");
      out.write("							<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/logoWHM.png\"\r\n");
      out.write("							alt=\"Women's Health Maternity\" />\r\n");
      out.write("						</a>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-lg-9 col-md-8 col-sm-6\">\r\n");
      out.write("						<button class=\"navbar-toggler\" type=\"button\"\r\n");
      out.write("							data-bs-toggle=\"collapse\" data-bs-target=\"#navbarNav\"\r\n");
      out.write("							aria-controls=\"navbarNav\" aria-expanded=\"false\"\r\n");
      out.write("							aria-label=\"Toggle navigation\">\r\n");
      out.write("							<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("						</button>\r\n");
      out.write("						<div class=\"collapse navbar-collapse\" id=\"navbarNav\">\r\n");
      out.write("							<ul class=\"navbar-nav ms-auto\">\r\n");
      out.write("								<!-- đặt khám -->\r\n");
      out.write("								<li class=\"nav-item dropdown\"><a\r\n");
      out.write("									class=\"nav-link dropdown-toggle\" href=\"#\" id=\"bookingDropdown\"\r\n");
      out.write("									role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("										Đặt lịch khám </a>\r\n");
      out.write("									<ul class=\"dropdown-menu\" aria-labelledby=\"bookingDropdown\">\r\n");
      out.write("										<li><a class=\"dropdown-item\" href=\"../BacSi/bacsi.html\">Bác\r\n");
      out.write("												sĩ</a></li>\r\n");
      out.write("										<li><a class=\"dropdown-item\"\r\n");
      out.write("											href=\"../CoSoYTe/coSoYTe.html\">Cơ sở y tế</a></li>\r\n");
      out.write("									</ul></li>\r\n");
      out.write("								<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("									href=\"../HoiDapBacSi/hoidap.html\">Hỏi đáp bác sĩ</a></li>\r\n");
      out.write("								<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("									href=\"../HoSoSucKhoe/hoSoSucKhoe.html\">Hồ sơ sức khỏe</a></li>\r\n");
      out.write("								<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("									href=\"../CamNang/camnang.html\">Cẩm nang</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</nav>\r\n");
      out.write("		<!--navbar end-->\r\n");
      out.write("	</header>\r\n");
      out.write("	<!--header end-->\r\n");
      out.write("	<script src=\"../../bootstrap/bootstrap.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("    <!-- body -->\r\n");
      out.write("    <div class=\"container main-panel\">\r\n");
      out.write("      <!-- panel thông tin bác sĩ -->\r\n");
      out.write("      <div class=\"panel-header d-flex\">\r\n");
      out.write("        <!-- Ảnh bác sĩ bên trái -->\r\n");
      out.write("        <div class=\"col-2 d-flex img-dichVu\">\r\n");
      out.write("          <img\r\n");
      out.write("            src=\"../../img/dichVu1.jpg\"\r\n");
      out.write("            alt=\"Ảnh dịch vụ\"\r\n");
      out.write("            class=\"img-fluid rounded\"\r\n");
      out.write("          />\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Thông tin bên phải -->\r\n");
      out.write("        <div class=\"col-9 d-flex flex-column\">\r\n");
      out.write("          <!-- Phần trên: Thông tin bác sĩ -->\r\n");
      out.write("          <div class=\"hospital-info\">\r\n");
      out.write("            <span class=\"hospital-name\">Bệnh viện 119 - Đà Nẵng</span>\r\n");
      out.write("            <p class=\"hospital-price\">700.000đ</p>\r\n");
      out.write("            <p class=\"hospital-specialty\">Khám Da Liễu</p>\r\n");
      out.write("            <div class=\"icon-item\">\r\n");
      out.write("              <i class=\"bi bi-star-fill\"></i> <span>4.5</span>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- panel thông tin dặt lịch -->\r\n");
      out.write("      <div class=\"col panel-lichkham\">\r\n");
      out.write("        <div class=\"d-flex mb-4 tuvan\">\r\n");
      out.write("          <h5>Lịch tư khám tại viện</h5>\r\n");
      out.write("          <select id=\"dropdown\" name=\"dropdown\" class=\"form-select w-auto\">\r\n");
      out.write("            <option value=\"2024-12-15\" selected>Ngày 15/12/2024</option>\r\n");
      out.write("            <option value=\"2024-12-16\">Ngày 16/12/2024</option>\r\n");
      out.write("            <option value=\"2024-12-17\">Ngày 17/12/2024</option>\r\n");
      out.write("          </select>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- time -->\r\n");
      out.write("        <div class=\"schedule-container\">\r\n");
      out.write("          <!-- Thêm các ô thời gian khác tại đây -->\r\n");
      out.write("          <div class=\"time-slot\">\r\n");
      out.write("            <a href=\"../view/appointmentInfor.jsp\">08:00</a>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"time-slot\">\r\n");
      out.write("            <a href=\"../view/appointmentInfor.jsp\">09:00</a>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"time-slot\">\r\n");
      out.write("            <a href=\"../view/appointmentInfor.jsp\">10:00</a>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"time-slot\">\r\n");
      out.write("            <a href=\"../ThongTinDatKham/thongTinDatKham.html\">11:00</a>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"time-slot\">\r\n");
      out.write("            <a href=\"../ThongTinDatKham/thongTinDatKham.html\">13:00</a>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"time-slot\">\r\n");
      out.write("            <a href=\"../ThongTinDatKham/thongTinDatKham.html\">14:00</a>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"time-slot\">\r\n");
      out.write("            <a href=\"../ThongTinDatKham/thongTinDatKham.html\">15:00</a>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"time-slot\">\r\n");
      out.write("            <a href=\"../ThongTinDatKham/thongTinDatKham.html\">16:00</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Kinh nghiệm học và làm -->\r\n");
      out.write("        <div class=\"col panel-kinhnghiem\">\r\n");
      out.write("          <!-- kinh nghiệm  -->\r\n");
      out.write("          <section class=\"kinhnghiem\">\r\n");
      out.write("            <h5>CHI TIẾT DỊCH VỤ</h5>\r\n");
      out.write("            <p>\r\n");
      out.write("              Xét nghiệm NIPT - 3 cặp nhiễm sắc thể là phương pháp xét nghiệm\r\n");
      out.write("              tiền sản, thường được thực hiện khi thai phụ ở tuần thứ 10, để\r\n");
      out.write("              phát hiện sớm những bất thường số lượng nhiễm sắc thể.\r\n");
      out.write("              <br />\r\n");
      out.write("              Kết quả xét nghiệm NIPT có độ chính xác cao, an toàn và được thực\r\n");
      out.write("              hiện đơn giản bằng phương pháp lấy mẫu máu xét nghiệm. Xét nghiệm\r\n");
      out.write("              NIPT - 3 cặp nhiễm sắc thể : Hội chứng Down (Trisomy 21); Hội\r\n");
      out.write("              chứng Edwards (Trisomy 18); Hội chứng Patau (Trisomy 13) và nhiễm\r\n");
      out.write("              sắc thể giới tính.\r\n");
      out.write("              <br />\r\n");
      out.write("              Xét nghiệm NIPT thường được chỉ định cho những đối tượng : - Phụ\r\n");
      out.write("              nữ trên 30 tuổi, đặc biệt là trên 35 tuổi<br />\r\n");
      out.write("              - Thai phụ có tiền sử bị thai lưu với mang thai dị dạng hoặc thai\r\n");
      out.write("              lưu không rõ nguyên nhân<br />\r\n");
      out.write("              - Thai phụ có kết quả siêu âm bất thường<br />\r\n");
      out.write("              - Kết quả xét nghiệm Double test/ Triple test nguy cơ cao<br />\r\n");
      out.write("              - Có thực hiện kỹ thuật hỗ trợ sinh sản (IVF)<br />\r\n");
      out.write("              - Mang đa thai<br />\r\n");
      out.write("              - Gia đình có tiền sử mắc bệnh di truyền<br />\r\n");
      out.write("              <br />\r\n");
      out.write("              Phòng khám Sản phụ khoa 43 Nguyễn Khang với thiết bị y tế hiện đại\r\n");
      out.write("              và đội ngũ y bác sĩ giàu kinh nghiệm, đã và đang cung cấp nhiều\r\n");
      out.write("              dịch vụ xét nghiệm chất lượng uy tín cho các sản phụ.\r\n");
      out.write("            </p>\r\n");
      out.write("          </section>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- footer -->\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("<title>Footer Example</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/footer.css\" />\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/bootstrap/bootstrap.min.css\" />\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css\"\r\n");
      out.write("	rel=\"stylesheet\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- Footer -->\r\n");
      out.write("	<footer class=\"container-fluid\">\r\n");
      out.write("		<!-- Logo and Social Icons Container -->\r\n");
      out.write("		<div class=\"footer-logo-icons\">\r\n");
      out.write("			<div class=\"footer-logo\">\r\n");
      out.write("				<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/logoP.png\" alt=\"Logo\" />\r\n");
      out.write("				<h2>WHM - Women's Health Maternity</h2>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- Phần Icon -->\r\n");
      out.write("			<div class=\"social-icons d-flex\">\r\n");
      out.write("				<a href=\"#\" class=\"me-4 text-reset\"> <i class=\"bi bi-facebook\"></i>\r\n");
      out.write("				</a> <a href=\"#\" class=\"me-4 text-reset\"> <i class=\"bi bi-instagram\"></i>\r\n");
      out.write("				</a> <a href=\"#\" class=\"me-4 text-reset\"> <i class=\"bi bi-whatsapp\"></i>\r\n");
      out.write("				</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- Section: Links -->\r\n");
      out.write("		<section class=\"footer-links\">\r\n");
      out.write("			<div class=\"row justify-content-between\">\r\n");
      out.write("				<!-- Contact Info -->\r\n");
      out.write("				<div class=\"col-md-3 col-lg-3 col-xl-3 mx-auto mb-4\">\r\n");
      out.write("					<h4 class=\"text-uppercase fw-bold mb-4\">Thông tin liên hệ</h4>\r\n");
      out.write("					<p>\r\n");
      out.write("						<i class=\"bi bi-geo-alt\"></i>Khoa Công Nghệ Thông Tin, Trường Đại\r\n");
      out.write("						Học Nông Lâm TP.Hồ Chí Minh\r\n");
      out.write("					</p>\r\n");
      out.write("					<p>\r\n");
      out.write("						<i class=\"bi bi-envelope-at\"></i> 22130078@st.hcmuaf.edu.vn<br>\r\n");
      out.write("						<i class=\"bi bi-envelope-at\"></i> 22130262@st.hcmuaf.edu.vn\r\n");
      out.write("					</p>\r\n");
      out.write("					</p>\r\n");
      out.write("					<p>\r\n");
      out.write("						<i class=\"bi bi-telephone\"></i>1808 1309\r\n");
      out.write("					</p>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<!-- Services -->\r\n");
      out.write("				<div class=\"col-md-2 col-lg-2 col-xl-2 mx-auto mb-4\">\r\n");
      out.write("					<h4 class=\"text-uppercase fw-bold mb-4\">Dịch vụ</h4>\r\n");
      out.write("					<p>\r\n");
      out.write("						<a href=\"#\" class=\"text-reset\">Đặt lịch khám</a>\r\n");
      out.write("					</p>\r\n");
      out.write("					<p>\r\n");
      out.write("						<a href=\"#\" class=\"text-reset\">Hỏi đáp bác sĩ</a>\r\n");
      out.write("					</p>\r\n");
      out.write("					<p>\r\n");
      out.write("						<a href=\"#\" class=\"text-reset\">Hồ sơ sức khỏe</a>\r\n");
      out.write("					</p>\r\n");
      out.write("					<p>\r\n");
      out.write("						<a href=\"#\" class=\"text-reset\">Cẩm nang y tế</a>\r\n");
      out.write("					</p>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<!-- Policies -->\r\n");
      out.write("				<div class=\"col-md-3 col-lg-2 col-xl-2 mx-auto mb-4\">\r\n");
      out.write("					<h4 class=\"text-uppercase fw-bold mb-4\">Chính sách</h4>\r\n");
      out.write("					<p>\r\n");
      out.write("						<a href=\"#\" class=\"text-reset\">Điều khoản sử dụng</a>\r\n");
      out.write("					</p>\r\n");
      out.write("					<p>\r\n");
      out.write("						<a href=\"#\" class=\"text-reset\">Chính sách bảo mật</a>\r\n");
      out.write("					</p>\r\n");
      out.write("					<p>\r\n");
      out.write("						<a href=\"#\" class=\"text-reset\">Quy chế hoạt động</a>\r\n");
      out.write("					</p>\r\n");
      out.write("					<p>\r\n");
      out.write("						<a href=\"#\" class=\"text-reset\">Trung tâm trợ giúp</a>\r\n");
      out.write("					</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</section>\r\n");
      out.write("		<!-- Section: Links -->\r\n");
      out.write("\r\n");
      out.write("		<!-- Copyright -->\r\n");
      out.write("		<div class=\"text-center p-4\">&copy; 2024 WHM - Women's Health\r\n");
      out.write("			Maternity. All rights reserved.</div>\r\n");
      out.write("		<!-- Copyright -->\r\n");
      out.write("	</footer>\r\n");
      out.write("	<!-- Footer -->\r\n");
      out.write("	<script src=\"../../bootstrap/bootstrap.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("    <!-- script -->\r\n");
      out.write("    <script src=\"../../bootstrap/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"../../bootstrap/bootstrap.bundle.js\"></script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
