/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.31
 * Generated at: 2025-01-07 12:50:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view.ViewShare;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"UTF-8\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("    <title>Footer Example</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../../css/footer.css\" />\r\n");
      out.write("    <!-- Bootstrap CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../../bootstrap/bootstrap.min.css\" />\r\n");
      out.write("    <link\r\n");
      out.write("      href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css\"\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("    />\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    <!-- Footer -->\r\n");
      out.write("    <footer class=\"container-fluid\">\r\n");
      out.write("        <!-- Logo and Social Icons Container -->\r\n");
      out.write("        <div\r\n");
      out.write("          class=\"footer-logo-icons\"\r\n");
      out.write("        >\r\n");
      out.write("          <div class=\"footer-logo\">\r\n");
      out.write("            <img src=\"../../img/logoP.png\" alt=\"Logo\" />\r\n");
      out.write("            <h2>WHM - Women's Health Maternity</h2>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- Phần Icon -->\r\n");
      out.write("          <div class=\"social-icons d-flex\">\r\n");
      out.write("            <a href=\"#\" class=\"me-4 text-reset\">\r\n");
      out.write("              <i class=\"bi bi-facebook\"></i>\r\n");
      out.write("            </a>\r\n");
      out.write("            <a href=\"#\" class=\"me-4 text-reset\">\r\n");
      out.write("              <i class=\"bi bi-instagram\"></i>\r\n");
      out.write("            </a>\r\n");
      out.write("            <a href=\"#\" class=\"me-4 text-reset\">\r\n");
      out.write("              <i class=\"bi bi-whatsapp\"></i>\r\n");
      out.write("            </a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Section: Links -->\r\n");
      out.write("      <section class=\"footer-links\">\r\n");
      out.write("        <div class=\"row justify-content-between\">\r\n");
      out.write("          <!-- Contact Info -->\r\n");
      out.write("          <div class=\"col-md-3 col-lg-3 col-xl-3 mx-auto mb-4\">\r\n");
      out.write("            <h4 class=\"text-uppercase fw-bold mb-4\">Thông tin liên hệ</h4>\r\n");
      out.write("            <p>\r\n");
      out.write("              <i class=\"bi bi-geo-alt\"></i>Khoa Công Nghệ Thông Tin, Trường Đại\r\n");
      out.write("              Học Nông Lâm TP.Hồ Chí Minh\r\n");
      out.write("            </p>\r\n");
      out.write("              <p><i class=\"bi bi-envelope-at\"></i>\r\n");
      out.write("              22130078@st.hcmuaf.edu.vn<br>\r\n");
      out.write("              <i class=\"bi bi-envelope-at\"></i>\r\n");
      out.write("              22130262@st.hcmuaf.edu.vn</p>\r\n");
      out.write("            </p>\r\n");
      out.write("            <p><i class=\"bi bi-telephone\"></i>1808 1309</p>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <!-- Services -->\r\n");
      out.write("          <div class=\"col-md-2 col-lg-2 col-xl-2 mx-auto mb-4\">\r\n");
      out.write("            <h4 class=\"text-uppercase fw-bold mb-4\">Dịch vụ</h4>\r\n");
      out.write("            <p><a href=\"#\" class=\"text-reset\">Đặt lịch khám</a></p>\r\n");
      out.write("            <p><a href=\"#\" class=\"text-reset\">Hỏi đáp bác sĩ</a></p>\r\n");
      out.write("            <p><a href=\"#\" class=\"text-reset\">Hồ sơ sức khỏe</a></p>\r\n");
      out.write("            <p><a href=\"#\" class=\"text-reset\">Cẩm nang y tế</a></p>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <!-- Policies -->\r\n");
      out.write("          <div class=\"col-md-3 col-lg-2 col-xl-2 mx-auto mb-4\">\r\n");
      out.write("            <h4 class=\"text-uppercase fw-bold mb-4\">Chính sách</h4>\r\n");
      out.write("            <p><a href=\"#\" class=\"text-reset\">Điều khoản sử dụng</a></p>\r\n");
      out.write("            <p><a href=\"#\" class=\"text-reset\">Chính sách bảo mật</a></p>\r\n");
      out.write("            <p><a href=\"#\" class=\"text-reset\">Quy chế hoạt động</a></p>\r\n");
      out.write("            <p><a href=\"#\" class=\"text-reset\">Trung tâm trợ giúp</a></p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </section>\r\n");
      out.write("      <!-- Section: Links -->\r\n");
      out.write("\r\n");
      out.write("      <!-- Copyright -->\r\n");
      out.write("      <div class=\"text-center p-4\">\r\n");
      out.write("        &copy; 2024 WHM - Women's Health Maternity. All rights reserved.\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- Copyright -->\r\n");
      out.write("    </footer>\r\n");
      out.write("    <!-- Footer -->\r\n");
      out.write("    <script src=\"../../bootstrap/bootstrap.min.js\"></script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
